[[main]]
    name = "Home"
    url = "#about"
    weight = 1

[[main]]
    name = "Posts"
    url = "#posts"
    weight = 2

[[main]]
    name = "Experience"
    url = "#experience"
    weight = 3

[[main]]
    name = "Accomplishments"
    url = "#accomplishments"
    weight = 4

[[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[main]]
  name = "Activities"
  url = "https://activity.nikstoyanov.me"
  weight = 7
