baseURL = "https://nikstoyanov.me"
theme = 'hugo-bearblog'
title = "Nikola Stoyanov"
author = "Nikola Stoyanov"
copyright = "Copyright © 2024, Nikola Stoyanov."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
	blog = "/:slug/"
	tags = "/blog/:slug"

[params]
	description = "Perosnal website"
	favicon = "images/favicon.png"
	images = ["images/share.png"]
	title = "Hugo ʕ•ᴥ•ʔ Bear"
	math = true

[markup]
	[markup.goldmark]
		[markup.goldmark.extensions]
			[markup.goldmark.extensions.passthrough]
				enable = true
				[markup.goldmark.extensions.passthrough.delimiters]
					block = [['\[', '\]'], ['$$', '$$']]
				        inline = [['\(', '\)'], ['$', '$']]
